name: flow_accounting
description: Premium All In One Accounting Application For All Platforms.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.0.2
  path:
  path_provider:
  wave: ^0.2.0
  blur: ^3.0.0
  simple_gradient_text: ^1.2.2
  palette_generator: ^0.3.2
  flutter_datetime_picker: ^1.5.1
  intl: ^0.17.0
  shamsi_date: ^1.0.1
  marquee: ^2.2.0
  flutter_typeahead: ^3.2.4
  flutter_slidable: ^1.2.0
  share_plus: ^3.0.4
  url_launcher: ^6.0.18
  lottie: ^1.2.1
  fluttertoast: ^8.0.8
  cached_network_image: ^3.2.0
  back_button_interceptor: ^5.0.2
  fl_chart: ^0.45.0
  image_picker: ^0.8.4+10
  add_2_calendar: ^2.1.3
  flutter_phoenix: ^1.0.0
  quick_actions: ^0.6.0+10
  syncfusion_flutter_barcodes: ^19.4.56
  flutter_barcode_scanner: ^2.0.0
  screenshot: ^1.2.3
  local_auth: ^1.1.11
  flutter_native_splash: ^2.1.5
  flutter_launcher_icons: ^0.9.2
  flutter_app_name: ^0.1.0
  status_bar_control: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/sign_up.json
    - pattern_card_background_one.png
    - pattern_card_background_two.png
    - pattern_card_background_three.png
    - pattern_card_background_four.png
    - pattern_card_background_five.png
    - input_background_pattern.png
    - add_credit_card_icon.png
    - add_profile_icon.png
    - go_previous_icon.png
    - share_icon.png
    - instagram_icon.png
    - search_shape.png
    - coins_icon.png
    - unknown_user.png
    - transactions_icon.png
    - sell_invoices_icon.png
    - buy_invoices_icon.png
    - products_icon.png
    - cheques_icon.png
    - debtors_icon.png
    - creditors_icon.png
    - customers_icon.png
    - budgets_icon.png
    - loans_icon.png
    - unknown_products.png
    - quick_save.png
    - support_icon.png
    - submit_icon.png
    - qr_code_icon.png
    - qr_scan_icon.png
    - print_icon.png
    - signature_icon.png
    - sync_icon.png
    - logo.png
    - logo_background.png

  fonts:
    - family: Sans
      fonts:
        - asset: fonts/sans.ttf
    - family: Numbers
      fonts:
        - asset: fonts/credit_card.ttf
    - family: FlowIcons
      fonts:
        - asset: assets/FlowIcons.ttf

flutter_native_splash:

  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # flutter pub run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # flutter pub run flutter_native_splash:remove

  # color or background_image is the only required parameter.  Use color to set the background
  # of your splash screen to a solid color.  Use background_image to set the background of your
  # splash screen to a png image.  This is useful for gradients. The image will be stretch to the
  # size of the app. Only one parameter can be used, color and background_image cannot both be set.
  color: "#0095ff"
  #background_image: "assets/logo_background.png"

  # Optional parameters are listed below.  To enable a parameter, uncomment the line by removing
  # the leading # character.

  # The image parameter allows you to specify an image used in the splash screen.  It must be a
  # png file and should be sized for 4x pixel density.
  image: assets/logo.png

  # The branding property allows you to specify an image used as branding in the splash screen.
  # It must be a png file. Currently, it is only supported for Android > v12 and iOS.
  branding: assets/logo.png

  # To position the branding image at the bottom of the screen you can use bottom, bottomRight,
  # and bottomLeft. The default values is bottom if not specified or specified something else.
  branding_mode: center

  # The color_dark, background_image_dark, image_dark, branding_dark are parameters that set the background
  # and image when the device is in dark mode. If they are not specified, the app will use the
  # parameters from above. If the image_dark parameter is specified, color_dark or
  # background_image_dark must be specified.  color_dark and background_image_dark cannot both be
  # set.
  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-logo_background.png"
  #image_dark: assets/splash-invert.png
  #branding_dark: assets/dart_dark.png

  # Android 12 handles the splash screen differently than previous versions.  Please visit
  # https://developer.android.com/guide/topics/ui/splash-screen
  # Following are Android 12 specific parameter.
  android_12:
  # The image parameter sets the splash screen icon image.  If this parameter is not specified,
  # the app's launcher icon will be used instead.
  # Please note that the splash screen will be clipped to a circle on the center of the screen.
  # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
  # 640 pixels in diameter.
  # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
  # 768 pixels in diameter.
  #image: assets/android12splash.png

  # App icon background color.
  #icon_background_color: "#111111"

  # The image_dark parameter and icon_background_color_dark set the image and icon background
  # color when the device is in dark mode. If they are not specified, the app will use the
  # parameters from above.
  #image_dark: assets/android12splash-invert.png
  #icon_background_color_dark: "#eeeeee"

  # The android, ios and web parameters can be used to disable generating a splash screen on a given
  # platform.
  android: true
  ios: true
  web: false

  # The position of the splash image can be set with android_gravity, ios_content_mode, and
  # web_image_mode parameters.  All default to center.
  #
  # android_gravity can be one of the following Android Gravity (see
  # https://developer.android.com/reference/android/view/Gravity): bottom, center,
  # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
  # fill_vertical, left, right, start, or top.
  #android_gravity: center
  #
  # ios_content_mode can be one of the following iOS UIView.ContentMode (see
  # https://developer.apple.com/documentation/uikit/uiview/contentmode): scaleToFill,
  # scaleAspectFit, scaleAspectFill, center, top, bottom, left, right, topLeft, topRight,
  # bottomLeft, or bottomRight.
  #ios_content_mode: center
  #
  # web_image_mode can be one of the following modes: center, contain, stretch, and cover.
  #web_image_mode: center

  # To hide the notification bar, use the fullscreen parameter.  Has no effect in web since web
  # has no notification bar.  Defaults to false.
  # NOTE: Unlike Android, iOS will not automatically show the notification bar when the app loads.
  #       To show the notification bar, add the following code to your Flutter app:
  #       WidgetsFlutterBinding.ensureInitialized();
  #       SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom, SystemUiOverlay.top]);
  #fullscreen: true

  # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s)
  # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
  # do not remove any spaces:
  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'

flutter_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/logo_ios.png"
  image_path_ios: "assets/logo_ios.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/logo_background.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/logo.png" # only available for Android 8.0 devices and above

flutter_app_name:
  name: "جریان اقتصادی"